- name: Prepare system
  hosts: all
  tasks:
    - name: Install python3
      apt:
        name: python3
        state: present
        update_cache: yes

    - name: Print current user
      command: whoami
      register: whoami_result

    - debug:
        var: whoami_result.stdout
