---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Überprüfe, ob Docker installiert ist
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Ausgabe anzeigen
      ansible.builtin.debug:
        var: docker_version.stdout
